# Generated by Django 4.1.3 on 2022-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_taskmodel_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='estado',
            field=models.CharField(choices=[('Incompleto', '0'), ('Proceso', '1'), ('Completado', '2')], default='incompleto', max_length=50),
        ),
    ]
