# Generated by Django 4.1.3 on 2022-12-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_taskmodel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='id_usuario',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='estado',
            field=models.CharField(default='Incompleto', max_length=50),
        ),
    ]
